### ISSUE TITLE
Add documentation about options

### ISSUE THREAD

**Issue by tir38** [runningcode/fladle#10]
You show how some of the options should be setup in the sample (https://github.com/runningcode/fladle/blob/master/sample/build.gradle#L21) It would be great if all of the supported Flank options were documented in the readme.

**Comment by runningcode** [comment]
@tir38 Thanks for asking for this. Documentation is really important!
Can you take a look at https://github.com/runningcode/fladle/commit/3acf3b5c69eeacfc0bf7f0774876074e3f2f621c and let me know if anything is missing or needs improvement?
