### ISSUE TITLE
Where should fladle be configured? Appmodule, root, library?

### ISSUE THREAD

**Issue by runningcode** [runningcode/fladle#106]
Make it clear in the docs that it should be applied to the application module.

**Comment by ccjernigan** [comment]
And perhaps update the example project with separate root build.gradle and application module build.gradle, because that's where I looked to try to figure this out but couldn't tell since there was just one build.gradle.

**Comment by runningcode** [comment]
Do you mean this sample? Where it is applied beneath the application `build.gradle`? https://github.com/runningcode/fladle/blob/master/sample/build.gradle#L3

Or the sample in the docs?

**Comment by ccjernigan** [comment]
Yes that linked sample.

The application plugin is applied but there's ambiguity as to whether fladle is supposed to be applied to a root build.gradle (without application) versus a module build.gradle (with application).

A sample with a root build.gradle without fladle plus a module build.gradle (with fladle and application) would eliminate that ambiguity.

**Comment by runningcode** [comment]
Ok, we might have a difference in how we're looking at this. Maybe our terminology is different. 😆 

In my mind, that sample has a root `build.gradle` without the fladle plugin applied and has a sub module with the `fladle` plugin applied next to the android application module.

Could you send a PR to improve this? I would really love to improve this case as I definitely can see how this could generate confusion. Thanks!

**Comment by ccjernigan** [comment]
I think I see where my confusion is coming from.

I was imagining the sample as a standalone project.  Like one could download the sample folder and build it without any surrounding context, like the parent directory. I didn't look to see that the root [settings.gradle](https://github.com/runningcode/fladle/blob/master/settings.gradle) includes the sample module.

So we currently have 1 gradle project that includes the fladle plugin and the sample.

I was imagining 2 gradle projects:
1. For fladle
2. For the sample

I'm guessing the current setup really helps with development of fladle as a test app, however it probably doesn't provide as good of a sample for others to copy.  (At least it was confusing for me 😅)

Would it be more clear if there was a sample in a separate repo, and then renaming the sample module in this repo to make it clear it is really a test app for developing fladle?

**Comment by runningcode** [comment]
Yeah! Actually it might make sense to have a separate sample repo. Good feedback.

**Comment by runningcode** [comment]
Hey! I've made this more clear in the setup: https://runningcode.github.io/fladle/quick-start/

Thanks for the feedback. While playing around I also realized that you can also apply and configure fladle in the root project if you wish. The only downside is that it will not be able to autodiscover your debug or instrumentation apk.
