### ISSUE TITLE
Support more Flank options

### ISSUE THREAD

**Issue by tir38** [runningcode/fladle#11]
After digging around, I see you support a limited set of Flank options:

https://github.com/runningcode/fladle/blob/a56cdf6e752181b8300b0313cc928c767494a947/buildSrc/src/main/java/com/osacky/flank/gradle/FlankGradleExtension.kt#L6

Can you add more options? Specifically setting `test-shard` would be helpful, since that's the main benefit of using Flank in the first place.

**Comment by runningcode** [comment]
Hey, thanks for the feature request. I looked around in the Flank repo and I couldn't find the string `test-shard`. Is this a gcloud option? Or Do you want it to map to the Flank `testShards` yml config option?

**Comment by winterDroid** [comment]
I agree that it would be nice to support essentially all parameters that gcloud and flank support. Might be difficult to keep both in sync though.. I think he means the `testShards` yes
