### ISSUE TITLE
Fetch specified flank jar automatically

### ISSUE THREAD

**Issue by dbarwacz** [runningcode/fladle#110]
Hello! 
I'm looking into fladle to add it as a lightway approach to running flank in library project. I'm surprised that I get error: 

`Execution failed for task ':example:app:execFlank'.
> Could not resolve all files for configuration ':example:app:fladle'.
   > Could not find flank:flank:8.1.0.
     Searched in the following locations:
       - file:/Users/user/.m2/repository/flank/flank/8.1.0/flank-8.1.0.pom
       - https://repo.maven.apache.org/maven2/flank/flank/8.1.0/flank-8.1.0.pom
       - https://dl.google.com/dl/android/maven2/flank/flank/8.1.0/flank-8.1.0.pom
       - https://jcenter.bintray.com/flank/flank/8.1.0/flank-8.1.0.pom
       - https://maven.google.com/flank/flank/8.1.0/flank-8.1.0.pom
       - https://plugins.gradle.org/m2/flank/flank/8.1.0/flank-8.1.0.pom
       - http://oss.sonatype.org/content/repositories/snapshots/flank/flank/8.1.0/flank-8.1.0.pom
     Required by:
         project :example:app
`
Does it mean that fladle does not attempt to download flank executable? Is there something wrong with my setup?

**Comment by runningcode** [comment]
Hi sorry, in the new version of fladle, which is what the docs are pointed at, you will not need to specify this since flank is now published to maven central.
In the meantime, the old version of flank is only in this repo so you will need to add this to your buildscript classpath:
```
repositories {
  maven { url 'https://dl.bintray.com/flank/maven' }
}
```

**Comment by runningcode** [comment]
Please re-open this issue if the above solution didn't work.
