### ISSUE TITLE
timeoutMin should be timeout with configuration of units

### ISSUE THREAD

**Issue by digitalbuddha** [runningcode/fladle#136]
Howdy! I have a request. I'd like to run robo-tests for 30s. Currently fladle only allows timeoutMin while flank allows timeout where I can set something like 30s.  Could we add that api to fladle as well. Thank you

**Comment by runningcode** [comment]
I honestly have no idea what the difference is between 
https://runningcode.github.io/fladle/configuration/#runtimeout and https://runningcode.github.io/fladle/configuration/#timeoutmin

@pawelpasterz can you shed some light here? What is the difference between those two values and what @digitalbuddha is asking for?

Also @digitalbuddha can you link the flank docs about this feature just so we're clear which one we're talking about?

**Comment by pawelpasterz** [comment]
[1] `runTimeout` -- time after flank cancels run. Before exiting process flank cancels all running matrices if there are any. It's flank's feature.

[2] `timeoutMin` --  time after which FTL cancels running tests/matrices. It's FTL's feature

[2] is send as parameter to FTL during matrix construction while [1] is flank's internal.

Let me know if my explanation is clear :)

**Comment by runningcode** [comment]
Yes, thank you very much! This would be a good opportunity for documentation improvements. :)

**Comment by digitalbuddha** [comment]
Hi friends, refer to this thread https://firebase-community.slack.com/archives/C1MTSQ5QT/p1591219224240200?thread_ts=1591218666.237500&cid=C1MTSQ5QT my understanding is that I should be able to set timeout as seconds and not just minutes.

**Comment by pawelpasterz** [comment]
Correct, flank supports different units. I think in fladle minutes are hardcoded
https://github.com/runningcode/fladle/blob/5ba419507ac4f2e694dde60431b9f6acd9260d32/buildSrc/src/main/java/com/osacky/flank/gradle/YamlWriter.kt#L103

**Comment by runningcode** [comment]
oh nice find. yes please do!

**Comment by runningcode** [comment]
Was released in 0.10.2
