### ISSUE TITLE
Support snapshot version

### ISSUE THREAD

**Issue by winterDroid** [runningcode/fladle#14]
It would be great to be able to use the latest snapshot version as well. Or to specify the jar file itself instead of downloading. Actually both options would be great!

**Comment by runningcode** [comment]
Just to be clear, you mean the snapshot of flank itself? :)

**Comment by winterDroid** [comment]
Yes to play around with the latest shiny features ^^

**Comment by runningcode** [comment]
@winterDroid Done! Check the readme for information on how to do this.

**Comment by winterDroid** [comment]
Great! Thx!
