### ISSUE TITLE
Duplicate status messages

### ISSUE THREAD

**Issue by jan-gogo** [runningcode/fladle#140]
**Describe the bug**
Running flank using fladle gives duplicated messages on output. 

**Details**
Flank provides 3 different types of output style [single, multi, verbose]. `--output-style=multi` is default when flank is running more than one execution. It is using ANSI codes to overwrite multiple lines in output. Some consoles may not supports ANSI codes so it can results with duplicated messages. Also running flank through gradle may give same results.

**To reproduce**
Run fladle with `max-test-shards`  > 1. It's important to have more than one shard. The expected result was pasted in issue https://github.com/Flank/flank/issues/841.

**Additional context**
* `--output-style=multi` displays separated status for each shard execution in separated line, lines are updated over time. Similar to gradle output when running multiple tasks in parallel. Requires ANSI codes support.
* `--output-style=single` displays shortened status of all executions in single line. Similar to gcloud output when running with sharding. Should work on any console.

**Possible solutions**
* Add option `output-style` to fladle so users can specify which one they want.
* Add `output-style=single` to executions under the hood so all executions on fladle will display single output.

**Comment by runningcode** [comment]
Thank you very much for the detailed report. I'll try to get to this as soon as I can. In the meantime, I always like to say, PR's welcome :).
