### ISSUE TITLE
Support new Flank options without the need to update Fladle

### ISSUE THREAD

**Issue by francescocervone** [runningcode/fladle#146]
**Problem**
Very often, Flank adds new configuration options. 
They are not usable from Fladle clients until Fladle does not release a new version that supports them.

**Proposal**
It would be great if Fladle exposed some property to the `FlankGradleExtension` that allows clients to put additional options not yet supported in the yaml configuration file.

**Some ideas**
I will just paste here some ideas, but I'm sure @runningcode will have some smarter and cleaner ones.
```kotlin
// Fladle plugin
interface FladleConfig {
  var testShards: Int?
  var shardTime: Int?
  // ...
  var additionalFlankOptions1: MapProperty<String, String> // Does not cover more complex options but it's simple
  var additionalFlankOptions2: MapProperty<String, Any> // Any can be an infinitely nested combination of Lists and Maps with String leaves
  var additionalFlankOptions3: Property<SomeJsonType> // A json that will be converted to Yaml
  var additionalFlankOptions4: Property<String> // A string that will be blindly appended to the Yaml file
}
```

**Comment by runningcode** [comment]
Hey thanks for the proposal. I'm kind of leaning toward the last option for now. Option 4. Let me think about this for a bit more
