### ISSUE TITLE
Write flank output to a task specific directory

### ISSUE THREAD

**Issue by runningcode** [runningcode/fladle#148]
In order to support running multiple simultaneous flank configs, we need to write the flank output to a task specific directory.
This likely involves configuring the command line output to write the files somewhere specific: https://github.com/runningcode/fladle/blob/master/buildSrc/src/main/java/com/osacky/flank/gradle/FladlePluginDelegate.kt#L90

See: https://github.com/runningcode/fladle/issues/141

**Comment by pawelpasterz** [comment]
@runningcode 
If you are ok with that, I'd like to implement this feature.

1. Fladle will reflect flank's default dir structure, example (for `oranges`):
    ```
    [root]/build/fladle/oranges/results
    ├── 2020-10-02_15-29-58.838153_lhtG
    │   ├── CostReport.txt
    │   ├── JUnitReport.xml
    │   ├── MatrixResultsReport.txt
    │   ├── flank.yml
    │   ├── matrix_0
    │   │   ├── NexusLowRes-28-en-portrait
    │   │   │   └── test_result_1.xml
    │   └── matrix_ids.json
    ```
   fladle will add additional dir with name `yyyy-mm-dd_hh-mm-ss.UUID`
1. Unless explicitly specified by the user (with `localResultDir.set("path/to/save/results")`) default configuration will be used.
1. Fladle default is overwritten with a user's provided path

Let me know what do you think

**Comment by runningcode** [comment]
That looks great! Please do that.
