### ISSUE TITLE
full-junit-result configuration is missing

### ISSUE THREAD

**Issue by kozaxinan** [runningcode/fladle#157]
`full-junit-result` is required parameter to have smart sharding. https://github.com/Flank/flank/issues/902 is reported on flank side. And according to flank source code

https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt#L133
will call
https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/gc/GcStorage.kt#L62 
for uplading the file. Without `full-junit-result` or `legacy-junit-result`, I failed to configure smart sharding. New logic and keyword is introduced in https://github.com/Flank/flank/pull/798.

**Comment by pawelpasterz** [comment]
This should be resolved once https://github.com/runningcode/fladle/pull/164 is merged

**Comment by kozaxinan** [comment]
@pawelpasterz Does fladle gradle plugin has property for `full-junit-result`?. I dont see new property added in to code or docs or examples in #164.

**Comment by runningcode** [comment]
Fixed in #170
