### ISSUE TITLE
Not possible to override Property values in individual configurations

### ISSUE THREAD

**Issue by damianw** [runningcode/fladle#158]
The construction of `FladleConfigImpl` for individual configs, [seen here](https://github.com/runningcode/fladle/blob/8ed7ca8f72d7c0d7aa7fe794543d78e62388b8df/buildSrc/src/main/java/com/osacky/flank/gradle/FlankGradleExtension.kt#L95-L133), passes all of the values directly. This is a problem for properties using the `Property` API: since the entire `Property` object is shared, the value cannot be overridden for individual configurations.

For example, in a configuration like this:
```Kotlin
fladle {
    // ...
    localResultsDir.set("output")
    configs {
        create("firstConfig") {
            // ...
            localResultsDir.set("output-firstConfig")
        }
        create("secondConfig") {
            // ...
            localResultsDir.set("output-secondConfig")
        }
    }
}
```

The result of this is that every config, including the root config, end up with `localResultsDir` set to `output-secondConfig`.

I'm not sure of the "right" way to fix this - at the very least there would need to be a new property I think... something like this?

```Kotlin
localResultsDir = project.objects.property<String>().value(project.provider { localResultsDir.get() })
```

**Comment by runningcode** [comment]
Yes, this is a very good point. Thanks for bringing it up so I can prioritize this. 

This is the reason we didn't merge these PRs: https://github.com/runningcode/fladle/pull/126#issuecomment-645754679

If the code you have written there works, please feel free to submit a PR!
