### ISSUE TITLE
Support for Robo Tests without Robo script

### ISSUE THREAD

**Issue by ccjernigan** [runningcode/fladle#165]
This is an enhancement request to support robo tests without a robo script.  Firebase Test Lab supports this, although it appears fladle does not. In the fladle source, the decision to do a robo test is based on the roboscript file path being non-null.

Issues sometimes come up with R8, ProGuard, or DexGuard that make robo testing the my release APK helpful in catching issues that might occur during first launch.  However, DexGuard also obfuscates resource IDs which makes creating a roboscript for a release build much more difficult.

Being able to launch a robo test without a roboscript will enable my use case, but would also lower the barrier for others who want to run a robo test without recording a script.

**Comment by runningcode** [comment]
Oh, I didn't realize this was a use case. Thanks for reporting. Do you know if flank itself supports this?

**Comment by runningcode** [comment]
Yes, flank supports this but you must specify `robo-directives` is that your use case?

**Comment by ccjernigan** [comment]
I was initially looking to effectively simulate prelaunch reports, without having to upload to Google Play.  I've tried running this directly with the gcloud command without roboscript or robo-directives, which works.

Let me check on what's involved with robo-directives, because maybe an empty set of robo-directives would work.

**Comment by runningcode** [comment]
Is the fix in fladle to allow a roboDirective to be specified without specifying a roboScript or an instrumentation APK? I can do this relatively quickly if this is what is needed. Please confirm. Thanks!

**Comment by ccjernigan** [comment]
I tried with flank, and it looks like it has a requirement that one of these be set:

```
java -jar flank.jar firebase test android run
version: v20.08.4
revision: 0b328fa775ebc69980b765b35a654089a6235d10

One of following options must be specified [test, robo-directives, robo-script].
```

I tried just setting fake robo-directives but it still would not run, so this looks like a limitation in flank currently.

**Comment by runningcode** [comment]
Ah, in that case, can you open an issue in the flank repository? Link it from here. It's likely we'll both need to make changes.

**Comment by ccjernigan** [comment]
https://github.com/Flank/flank/issues/1084

**Comment by ccjernigan** [comment]
FYI the underlying Flank issue was just resolved 🎉

**Comment by runningcode** [comment]
Please do! Thanks!
