### ISSUE TITLE
Custom debugApk setting gets overwritten if instrumentationApk is not set

### ISSUE THREAD

**Issue by Egorand** [runningcode/fladle#172]
Our project has the following configuration:

```groovy
fladle {
  variant = "internalDebug"

  debugApk = project.provider {
    "$buildDir/outputs/apk/internal/debug/app-internal-debug-universal.apk"
  }
}
```

Surprisingly, this fails with the following error:

```
'/.../app/build/outputs/apk/internal/debug/app-internal-debug.apk' not found 
```

From looking at the code, it seems that if either `debugApk` or `instrumentationApk` is not set the plugin will try to locate those files automatically, overwriting `debugApk` in the process:

https://github.com/runningcode/fladle/blob/d33223104a11446ea9b64868d64cc81ff50e36c1/buildSrc/src/main/java/com/osacky/flank/gradle/FladlePluginDelegate.kt#L45-L47

Indeed, providing the default path to the instrumentation APK explicitly resolves the issue:

```groovy
fladle {
  variant = "internalDebug"

  debugApk = project.provider {
    "$buildDir/outputs/apk/internal/debug/app-internal-debug-universal.apk"
  }
  instrumentationApk = project.provider {
    "$buildDir/outputs/apk/androidTest/internal/debug/app-internal-debug-androidTest.apk"
  }
}
```

`debugApk` and `instrumentationApk` should probably be resolved independently to support use cases where one of the values is a custom path while the other is default.

**Comment by runningcode** [comment]
@Egorand thanks for the detailed bug report and explanation. That makes sense to resolve them independently for this use case.

I'm curious, does using fulladle work here? https://runningcode.github.io/fladle/multi-module-testing/

I ask because it resolves the apks at execution time instead of configuration time and I'm wondering if it just works here.

**Comment by runningcode** [comment]
Please try [0.12.1](https://runningcode.github.io/fladle/changelog/#0121) and let me know how it works.

**Comment by Egorand** [comment]
Hey Nelson, thanks for the quick fix! Haven't managed to try fulladle, but fladle 0.12.1 works perfectly!
