### ISSUE TITLE
Question on: "An infrastructure error occurred. Retrying.."

### ISSUE THREAD

**Issue by pjakubczyk** [runningcode/fladle#178]
Is there a trace somewhere in flank directory that the
`Error: An infrastructure error occurred. Retrying..`
occurred ?
I would like to gather data regarding success ratio on my tests including how much time it took. I saw that each time this error shows up in logs the suite is being restarted on a new device. This of course takes time (not blaming Fladle for that :) ) and I'd like to have it somewhere reported.

**Comment by runningcode** [comment]
That's a great question for Flank. I am unsure what kinds of logs they store. By default when using fladle all flank output is placed somewhere in the `build/flank` directory. Check there for more information otherwise please file an issue with flank: https://github.com/flank/flank
