### ISSUE TITLE
How to set results-history-name?

### ISSUE THREAD

**Issue by blundell** [runningcode/fladle#180]
I can see in the changelog you added support for "setting results-history-name"

![image](https://user-images.githubusercontent.com/655860/94416567-eaae6b00-0176-11eb-813a-e48e0654d0ab.png)
https://runningcode.github.io/fladle/changelog/

which is this: 
https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run#--results-history-name
![image](https://user-images.githubusercontent.com/655860/94416762-23e6db00-0177-11eb-83b1-3a93e363e424.png)

But I can't see it's use explained in the configuration page: https://runningcode.github.io/fladle/configuration/

**Comment by runningcode** [comment]
Thanks for pointing this out. I'll update the documentation.
In the meantime, you can set it with the property `resultsHistoryName = "foo"`.
