### ISSUE TITLE
Setting the FlankGradleExtension properties from another plugin

### ISSUE THREAD

**Issue by satyarths** [runningcode/fladle#191]
Hi there,

I've created a wrapper plugin (similar to Fulladle) to configure fladle on a multi-module project. Populating the FlankGradleExtension is done using a wrapper plugin. 

```
        val flankGradleExtension = root.extensions.getByType(
                FlankGradleExtension::class
        )
        with(flankGradleExtension) {
            environmentVariables = mapOf(
                    "coverage" to "true",
                    "coverageFilePath" to "/sdcard/coverage.ec"
            )
            projectId = "id"
            serviceAccountCredentials.set(
                    root.layout.projectDirectory.file(
                            "firebase-credentials.json"
                    )
            )
            useOrchestrator = true
            directoriesToPull = listOf("/sdcard/")
            filesToDownload = listOf(".*/sdcard/[^/]+\\.ec\$")
            localResultsDir.set("${root.buildDir.path}/flank/results")
            recordVideo = true
            performanceMetrics = true

        }
```

However the latest release marks these values as immutable , and hence cannot be updated. My requirement is to have fladle configured via a plugin (instead of the root build.gradle).  Would you have any suggestions on how could achieve this now and if this seems like a correct approach to do this.

**Comment by runningcode** [comment]
Hi there! That seems pretty cool. I would love to know more about your use case and see if I can incorporate it in fulladle mainline!

That being said, if you are using the kotlin language (as it looks from the snippet you sent) I would recommend checking the documentation on how to set values such as [projectId](https://runningcode.github.io/fladle/configuration/#projectid).
The api is slightly different for kotlin.

The release notes document this [breaking API change in 0.13.0](https://runningcode.github.io/fladle/changelog/#0130)

**Comment by satyarths** [comment]
Ah right. I guess this would qualify more as my lack of gradle knowledge. Thank you for the quick reply. I'll try this out and get back to you.

**Comment by satyarths** [comment]
Yup this works perfectly..Thank you very much!!  apologies for not RTFM-ing before posting. 😓

**Comment by runningcode** [comment]
Happy to help!
