### ISSUE TITLE
Feature Request: Omit modules with fulladle

### ISSUE THREAD

**Issue by arlindiDev** [runningcode/fladle#202]
When using Fulladle, It would be great to have an option to omit modules so the modules `apk` and `testApk` are not added to the fladle config

**Comment by runningcode** [comment]
This is a good feature request. I'm thinking of two possible APIs for this.
1. In the module we want to exclude add a small fulladle configuration:
```
fulladle {
  exclude = true
```

2. In the root module, list modules which we would like to exclude:
```
fladle {
  fulladleExcludes = [ ":player-feature:ui", "player-feature:db" ]
}
```

I think the former one makes a bit more sense to me. What are your thoughts?

**Comment by arlindiDev** [comment]
Yea the second one looks better

**Comment by runningcode** [comment]
@arlindiDev, why do you prefer the second one instead of the first one? I was thinking that the first one is a better idea because keeping track of module names seems complicated and renames and refactors will break things.
