### ISSUE TITLE
Add option to output flank.yml file for debugging

### ISSUE THREAD

**Issue by bootstraponline** [runningcode/fladle#216]
For debugging purposes, it's helpful to take a `flank.yml` file and run this with both gcloud and Flank. This enables isolating the problem to Flank or gcloud. If a feature works in gloud and fails in Flank, then it's a Flank bug. If it fails in gcloud, then it's likely a FTL service issue that Flank can't resolve.

What do you think about adding a mode to fladle where it will output the flank.yml file it's using to disk to improve debugging?

**Comment by runningcode** [comment]
Do you mean having a task like `./gradlew printYml`? This task would read the yaml file from disk and print it out to the console?

Try running `./gradlew printYml` in your set up and let me know what is missing!

**Comment by jan-gogo** [comment]
@bootstraponline The proposition is to add a new option to `fladle` for displaying `flank.yml` config to output on `./gradlew flankRun` execution? Correct me if I'm wrong.

**Comment by runningcode** [comment]
You can also do
```
tasks.named("runFlank").configure {
    dependsOn(tasks.named("printYml"))
}
```
to print it out on every run if you like.

**Comment by bootstraponline** [comment]
The usual Flank workflow (without Fladle) is this:

1. User creates `flank.yml` and invokes `flank run android`
2. If a bug is observed, user runs `gcloud firebase test android run flank.yml:gcloud`
3. If the bug reproduces with gcloud, then it's unlikely to be a problem in Flank itself.

The ask here is for Fladle to optionally write the configuration to disk, so that users may run the same yaml config with gcloud to enable fault isolation. What do you think?

**Comment by runningcode** [comment]
The `flank.yml` is always written to `<project>/build/fladle/flank.yml` by default whenever `runFlank` or `printYml` is executed. You can configure a copy task to copy the output to wherever you like or copy the file manually from the filesystem.

**Comment by bootstraponline** [comment]
Nice, I didn't know that. The steps are to run `./gradlew printYml` and then look in `<project>/build/fladle/flank.yml` I think that's exactly what we need.
