### ISSUE TITLE
Compiler not recognising 'additionalFlankOptions' as part of fladle extension

### ISSUE THREAD

**Issue by wesleywen1** [runningcode/fladle#218]
Hi, 

With the latest commit to master I noticed the much anticipated 'additionalFlankOptions' config option and tried to implement it with the latest fladle version 0.14.0. However I'm getting the following error when compiling: 

> Could not set unknown property 'additionalFlankOptions' for extension 'fladle' of type com.osacky.flank.gradle.FlankGradleExtension.

Could you please confirm if this is because this change was not included as part of the latest fladle version? And if so when a new version will be published to maven including this change?

**Comment by runningcode** [comment]
This is true. It is still in the unreleased section of the changelog. Unfortunately the docs are not versioned.
https://runningcode.github.io/fladle/changelog/#unreleased

What features are you looking to support? Please file an issue so we can add them in before making the release!

**Comment by wesleywen1** [comment]
Thanks for the reply! I'll file an issue first thing tomorrow. I found a few workarounds for the additionalFlankOptions config but I was still hoping to support one of the gcloud options specifically the 'async' option - The use case for us is that when running Fladle from the CI it would be awesome if we could choose to execute the tests asynchronously without having our build agent spending copious amounts of time awaiting the test results to return

**Comment by runningcode** [comment]
The automatically published snapshot version of fladle should already have the feature: https://runningcode.github.io/fladle/snapshots/

**Comment by wesleywen1** [comment]
Sweet I wasn't aware that it automatically publishes a snapshot. Thanks for your help once again & for all the work you do for the community! :)
