### ISSUE TITLE
Running different test suites on different types of devices.

### ISSUE THREAD

**Issue by satyarths** [runningcode/fladle#219]
Hi there,

Would  it be possible to run specific  tests  on different  devices? For example, run performance tests on physical devices while running regression tests on virtual devices.

I'm not sure if this  is a fladle or flank issue. So please let me know and I can  close/change as needed . 

Thanks!

**Comment by runningcode** [comment]
Hi @satyarths , sorry the delayed response.

Here's a sample in groovy dsl
```
fladle {
    configs {
        perfTests {
            devices = [ "model" : "Nexus5", "version" : "28" ],
            testTargets = [
                "class com.sample.MyPerformanceTest"
            ]
        }
        regressionTests {
            devices = [ "model" : "Nexus5LowRes", "version" : "28" ],
            testTargets = [
                "class com.sample.MyRegressionTest"
            ]
        }
    }
}
```
If you need it in the kotlin dsl, you should be able to map the values from the documentation here: https://runningcode.github.io/fladle/configuration/

Let me know if you run in to any troubles or need any further help.

**Comment by satyarths** [comment]
Thanks @runningcode, This helps. Closing the ticket now, and I'll get back to you once I try it out!
