### ISSUE TITLE
Feature request: Force latest Flank version 

### ISSUE THREAD

**Issue by wesleywen1** [runningcode/fladle#222]
It would be great if there was a flag for us to force Fladle to use the latest Flank version (something like --forcelatest).

**Comment by runningcode** [comment]
You can declare a dynamic version using dynamic version declaration in Gradle: https://docs.gradle.org/current/userguide/dynamic_versions.html#sub:declaring_dependency_with_dynamic_version

For example: `flankVersion = "21.+"`

**Comment by runningcode** [comment]
I've added a recipe to this to the recipes page. https://runningcode.github.io/fladle/recipes/#always-use-the-latest-version-of-flank
