### ISSUE TITLE
dependOnAssemble = true builds all variants

### ISSUE THREAD

**Issue by AndrewReitz** [runningcode/fladle#233]
`dependOnAssemble = true` builds all variants of an application rather than just the one flank needs to run the tests.

This appears to be related to #60, if fladle doesn't know what variant apks it needs, it makes sense that it wouldn't know which to build.

**Comment by runningcode** [comment]
@AndrewReitz thanks for reporting this.

@asadsalman do you have any thoughts here?
https://github.com/runningcode/fladle/blob/master/fladle-plugin/src/main/java/com/osacky/flank/gradle/FladlePluginDelegate.kt#L111

**Comment by runningcode** [comment]
@AndrewReitz do you have a build scan that demonstrates this? If not can you name the flank task as well as the dependent `assemble` tasks that are being run? Do you have multiple flavors configured? Do you run a single instrumentation test task against multiple flavors?

I added a simple test case for this. https://github.com/runningcode/fladle/pull/234/files#diff-fae81d6619b0f02b12c40c2f9c567d2dd485e2c6c5bf8c2d072626cad86f3285R183

**Comment by runningcode** [comment]
I created #235 to use the extension's variant to determine which variant to depend on. Does this help?

**Comment by AndrewReitz** [comment]
@runningcode the tests look like I'm looking for trying out the snapshot now!
Thanks

**Comment by runningcode** [comment]
Thanks for testing. Please report back. I think I missed a test case (when no flavors are declared) so I will write this test case and make sure it works before releasing.

**Comment by AndrewReitz** [comment]
I'm trying to run it but the snapshot seems to have issues authenticating against FTL.

 I am getting
```
{
  "code": 403,
  "errors": [
    {
      "domain": "global",
      "message": "The caller does not have permission",
      "reason": "forbidden"
    }
  ],
  "message": "The caller does not have permission",
  "status": "PERMISSION_DENIED"
}
```

I ran `flankAuth` just to be sure, but no luck. Switching back to 15.0.0 and it's fine.
Is there something I should do differently or is there an issue with the SNAPSHOT?

I can get you the logs and output of stacktrace if that would be helpful.

**Comment by runningcode** [comment]
This seems to be an issue with the latest version of flank. Thanks for reporting. Can you set `flankVersion = '21.01.1'`

**Comment by AndrewReitz** [comment]
@runningcode this works as in it only builds one APK, but it's the last one that was set with `variant.set`. 
We have multiple configurations for running different apks or different flavors, as well as different sets of tests. 
So it seems #60 is the issue we are running into now. Let me know if I can help out in anyway.

**Comment by runningcode** [comment]
Thanks for testing @AndrewReitz can you give an example of your flavors and the fladle config and what dependencies you would expect to happen?

**Comment by AndrewReitz** [comment]
Here's an example of how things are setup. Left out a lot and just trying to highlight the issue. So in the case below if I don't specifically set the apks forr any of the product flavors the `bBetaDebug` apk will be used for all the different configs. If I set the apk explicitly it will be used for the tests but dependsOnAssemble will only build `bBetaDebug`. I can write a test case to show the error in fladle if that would help out.

```
 flavorDimensions "market", "mode"

  productFlavors {
    standard {
        dimension "mode"
    }
    beta {
        dimension "mode"
    }

    a {
        dimension "market"
    }
    b {
        dimension "market"
    }
    c {
        dimension "market"
    }
}

fladle {
    configs {
        standard {
            variant.set('aStandardDebug')
        }
        standardPr {
            variant.set('aStandardDebug')
            // only run subset of tests
        }
        standardDaggerReflect {
            variant.set('aStandardDebug')
        }
        regression {
            variant.set('aStandardDebug')
            testTargets.set(['annotation com.example.regression.Regression'])
        }
        beta {
            variant.set('bBetaDebug')
        }
    }
}
```

**Comment by runningcode** [comment]
Thanks for the clear example. The API was originally only designed to handle one variant. I did not imagine such a use case. The API needs to be changed. Will take a look at this soon hopefully.
