### ISSUE TITLE
Recommendation for shard times

### ISSUE THREAD

**Issue by pjakubczyk** [runningcode/fladle#254]
Hey,

I have rather a general question. In my project we have around 1000 small UI tests running for each PullRequest. 
The current configuration is `shardTime = 120` so just 2 minutes and wIth `smartFlankGcsPath` the distribution over emulator is working really great. We're launching ~250 emulator a build.
Recently I'm seeing more `"Quota exceeded for quota metric 'Queries' and limit 'Queries per day' of service 'toolresults.googleapis.com'` issues like that.
I'm wondering if there's recommendation on shartTime for such heavy load on Firebase Test Lab ?
Is it better to have more time in shards to spin less emulator?

wdyt ?

**Comment by runningcode** [comment]
Hey, thanks for asking. This is a good question for the underlying tool, Flank. https://github.com/flank/flank
I would file a bug there or in the firebase community slack and also mention the flank verison you are using. However, it might be out of their control. It might help to ask Google support to raise the limit for your use case.

**Comment by pjakubczyk** [comment]
Found Slack channel for FTL. Thanks
