### ISSUE TITLE
Set assemble parameter

### ISSUE THREAD

**Issue by BugsBunnyBR** [runningcode/fladle#268]
When using `dependOnAssemble = true` would it be possible to set a parameter to the build ?

Today I have to do set `dependOnAssemble=false` and run something like
`./gradlew assembleBlaBlaDebug -Pvariable=true` before running the flank tasks.

**Comment by runningcode** [comment]
You can customize the execution of the FlankExec task however you like:
```
tasks.withType(FlankJavaExec.class).configureEach {
// configure here
}
```

Is that what you need?

**Comment by BugsBunnyBR** [comment]
I am not sure, I would like to give the compilation task an extra parameter in a given fladle config.

I found that the same parameter that I use to assemble the apk can be given to the fladle task and it will be available at the to the assemble task.
So... both commands below will work in regards of reading `-Pvariable=true`.
``` 
./gradlew assembleBlaBlaDebug -Pvariable=true
./gradlew runFlank -Pvariable=true 
```

Sorry for the trouble.
