### ISSUE TITLE
environmentVariables are not passed to flank.yml

### ISSUE THREAD

**Issue by kozaxinan** [runningcode/fladle#270]
We have environmentVairables in fladle block.

```
environmentVariables = [
      "clearPackageData": "true",
      "listener"        : "a.b.c.Foo1" +
               "a.b.c.Foo2"
  ] 
```
environmentVairables are not present in flank.yml and they are not passed to test run on firebase.

**Comment by runningcode** [comment]
Thanks for filing. Do you know if there was a specific version where this stopped working?

**Comment by kozaxinan** [comment]
It works with 0.15.1.
We are using fulladle plugin with flank 21.09.0.
I will test 0.16.0

**Comment by kozaxinan** [comment]
It works on 0.16.0 as well. I couldnt test with 0.16.1.

**Comment by kozaxinan** [comment]
Working versions has a warnings that latest version doesnt have.
```
WARNING: environment-variables set but directories-to-pull is empty, this will result in the coverage file  not downloading to the bucket

```

**Comment by kozaxinan** [comment]
We also don't have any `environment-variables:` in flank yml file even with working scenario. I am not sure how fulladle/fladle/flank passed the `environment-variables:` to firebase/gcloud.

I tried writing test but I couldn't reproduce anything because for us working and non working fladle versions create same yml file. Issue could be in different place not in yml file.

I can provide details if you need.
