### ISSUE TITLE
Unable to set environmentVariables

### ISSUE THREAD

**Issue by ronaldvanduren** [runningcode/fladle#28]
When trying to set the environmentVariables parameter in the Fladle block, I get the following error: Could not set unknown property 'environmentVariables' for object of type com.osacky.flank.gradle.FlankGradleExtension.

**Comment by winterDroid** [comment]
The version that's going to support it is not yet released.

**Comment by ronaldvanduren** [comment]
Ah, that's unfortunate. It might be a good idea then to mention this at the Optional Configuration part.

**Comment by runningcode** [comment]
Hey, sorry, not sure I understood what you would like to mention in the documentation. Can you make a pull request? I would love to improve the documentation. 

I'll be making a release with these changes in the next day or less!

**Comment by runningcode** [comment]
Please try version 0.4.0. It has support for environmentVariables. And please open up a new issue/PR for any documentation updates we are missing.
