### ISSUE TITLE
Is it possible to configure the JVM that's spawned to run flank?

### ISSUE THREAD

**Issue by inktomi** [runningcode/fladle#294]
I'm looking for a way to pass flags into the JVM that Flank runs under - but without using the same flags for other JVMs (like the one used to build the test artifacts). Because I can't use one set of flags for everything, I can't use `JAVA_OPTS` and that sort of thing. Is there a way to configure Flank's JVM?

**Comment by runningcode** [comment]
Thanks for filing. What are you trying to solve with these parameters?

**Comment by runningcode** [comment]
I will close this issue in 7 days if there isn't any more information here.

**Comment by inktomi** [comment]
We're seeing issues with out of memory errors and things like that. I'd like to tune the JVM used by flank specifically, rather than using the same flags as we'd use to build the binaries (for instance). Sorry for the delay!

**Comment by runningcode** [comment]
Thanks. Does configuring the tasks's `maxHeapSize` solve your use case?

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:maxHeapSize

```
tasks.withType(FlankExecutionTask).configureEach {
  maxHeapSize = "2g"
}
```

**Comment by runningcode** [comment]
That being said, it might make sense to open a bug against Flank if it is using so much memory. Calculating shards and uploading APKs shouldn't take up so much memory.

**Comment by runningcode** [comment]
Closing since this is configurable on the task itself.
