### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by ronaldvanduren** [runningcode/fladle#31]
When trying to add a new device as an optional parameter, the device object is not found on the classpath com.osacky.flank.gradle.Device. I'm using the following fladle block: 

apply plugin: "com.osacky.fladle"

import com.osacky.flank.gradle.Device 

fladle {
    // Required parameters
    serviceAccountCredentials("${project.file("path-to-key-file.json")}")

    // Optional parameters
    useOrchestrator = true

    environmentVariables = ["annotation": "some-annotation"]

    directoriesToPull = [
            "/sdcard/screenshots"
    ]
    filesToDownload = [
            ".*/screenshots/.*"
    ]
    timeoutMin = 15
    recordVideo = true
    performanceMetrics = false
    devices = [
            new Device("Pixel2", 28, null, null),
    ]
    flankVersion("v4.3.1")
    debugApk("$buildDir/outputs/apk/debug/app-debug.apk")
    instrumentationApk("$buildDir/outputs/apk/androidTest/debug/app-debug-androidTest.apk" )
    autoGoogleLogin = true
    testShards = 15
}

I'm using Gradle 5.2.1 and Gradle Plugin 3.3.0.

**Comment by runningcode** [comment]
Thanks for the report.
Can you copy a stacktrace here if possible?
What version of flank were you using?

**Comment by runningcode** [comment]
Also can you add the code of where you added the fladle plugin to the classpath?

**Comment by winterDroid** [comment]
@runningcode I have the same issue. But it seems to me just to be an IDE issue since it is still compiling just fine. Also happens to me with other Gradle plugins.

**Comment by runningcode** [comment]
Thanks for filing. I'm going to close this as bug in Intellij/AS.

We can also alternatively propose a different API which wouldn't require a dependency on a class in the plugin to make it easier to use. Please feel free to make an issue with a suggestion!
