### ISSUE TITLE
Unauthorized response from firebase

### ISSUE THREAD

**Issue by ronaldvanduren** [runningcode/fladle#32]
When trying to run ./gradlew runFlank, I get the following response back: 
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Forbidden",
    "reason" : "forbidden"
  } ],
  "message" : "Forbidden"
}

When using Flank on the command line with exactly the same Service Account Credentials everything works fine.

**Comment by runningcode** [comment]
Thanks for the report, in order to debug, can you paste the part of your gradle config where you are specifying the service account credentials?

**Comment by ronaldvanduren** [comment]
serviceAccountCredentials("${project.file("path-to-key-file.json")}")

**Comment by runningcode** [comment]
Was there any other information in the build above or below the error? 

Can you run `./gradlew printYml` and paste it here?

**Comment by ronaldvanduren** [comment]
It turned out it was a mistake on my side. I forgot to change to projectId variable.
