### ISSUE TITLE
Run screenshot tests using Shot plugin or Facebook plugin

### ISSUE THREAD

**Issue by vyguera** [runningcode/fladle#321]
Hi

I'm trying to run some screenshot tests with [Shot](https://github.com/pedrovgs/Shot) or with [Facebook Screenshot test for android](https://github.com/facebook/screenshot-tests-for-android) in my CI server using FTL.

Currently I already using Fladle for my UI tests along with [flank](https://github.com/Flank/flank) but both screenshot testing plugins uses a certain gradle task to validate the tests and as long as I understand fladle first requires the apk to be assemble and the run the UI tests. I haven't found any way to run a different gradle task using flank.

Is there any way to do it?

My goal is to run something similar to:
`./gradlew execFlank executeScreenshotTests`

**Comment by runningcode** [comment]
Aside from Fladle do they have documentation on how to run those tests on firebase test lab? Are they compatible with that? If so I can find a way to execute them with fladle if you point me to that. Otherwise, I don't think they are compatible.
