### ISSUE TITLE
can't find debugApk despite being configured manually

### ISSUE THREAD

**Issue by kenyee** [runningcode/fladle#43]
When I "runFlank", it complains that "buildApk cannot be null".  Autodetection failed (would be nice to have autodetection print out where it's looking).
So I specified the paths directly.

app build.config looks like (also tried moving this into the root build.gradle but that didn't work either):

``` 
// command line: gradle clean assembleKayakFreeDebug assembleKayakFreeAndroidTest runFlank
apply plugin: "com.osacky.fladle"
fladle {
    serviceAccountCredentials("${project.file("flank-gradle-service-account.json")}")
    directoriesToPull = [
            "/sdcard/screenshots"
    ]
    filesToDownload = [
            ".*/screenshots/.*"
    ]
    testTargets = [
            "class com.kayak.android.BasicLoginTest",
            "class com.kayak.android.BasicSearchTest"
    ]
    debugApk("$buildDir/outputs/apk/kayakFree/debug/KAYAK-kayakFree-debug-9999.0-9999.apk")
    instrumentationApk("$buildDir/outputs/apk/androidTest/kayakFree/debug/KayakTravelApp-kayakFree-debug-androidTest.apk")
}
```

**Comment by runningcode** [comment]
Thanks for the bug report. Sorry this is happening. To clarify, is this the stacktrace that happens when you are trying to auto-detect the apk location?
Another question, do you have the `fladle {` block before or after the `android {` one?
Thanks

**Comment by kenyee** [comment]
that's the same backtrace w/ and w/o the debugApk manually specified.
The fladle block is after the android{} on in the app dir's build.gradle.

No need to be sorry...bugs happen.  Let me know if there's some sort of debug mode I can run that would show where it's looking for the debugApk?  I'm confused as to why it's still null after specifying it though...

**Comment by runningcode** [comment]
can you paste the output of `./gradlew printYml`?
could you also try `./gradlew flankDoctor`? 

also what versions of gradle, fladle and flank are you using?

**Comment by kenyee** [comment]
Gradle version 5.3.1, Fladle 0.5.1, didn't specify a flank version so I assume it's the latest.

```
> Task :printYml FAILED

> Task :KayakTravelApp:printYml
gcloud:
  app: /Users/kyee/work/r9/android/KayakTravelApp/build/outputs/apk/kayakFree/debug/KAYAK-kayakFree-debug-9999.0-9999.apk
  test: /Users/kyee/work/r9/android/KayakTravelApp/build/outputs/apk/androidTest/kayakFree/debug/KayakTravelApp-kayakFree-debug-androidTest.apk
# projectId will be automatically discovered
  device:
  - model: NexusLowRes
    version: 28

  use-orchestrator: false
  auto-google-login: false
  record-video: true
  performance-metrics: true
  timeout: 15m
  test-targets:
  - class com.kayak.android.BasicLoginTest
  - class com.kayak.android.BasicSearchTest
  directories-to-pull:
  - /sdcard/screenshots
  flaky-test-attempts: 0

flank:
  files-to-download:
  - .*/screenshots/.*


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':printYml'.
> debugApk cannot be null
```

flankDoctor barfs out writing the config so it never finishes:
```
> Task :writeConfigProps FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':writeConfigProps'.
> debugApk cannot be null
```

Also, is there any way to specify a testrunner?  We don't use the standard JUnit4TestRunner.

**Comment by runningcode** [comment]
What do you have inside the fladle config in your root build.gradle? Does
your root build.gradle have a com.android.application plugin applied to it?

Ken Yee <notifications@github.com> schrieb am Di., 2. Apr. 2019, 21:29:

**Comment by kenyee** [comment]
Sorry for the late reply...I don't have a fladle config in my root build.gradle...the docs for fladle didn't say to add one there.
The root build.gradle doesn't have android applied to it.  Root gradle doesn't do much...library version info, defines a few plugins, sonar setup, library version checker.

**Comment by runningcode** [comment]
The fix is to not apply the fladle plugin in your root build.gradle file.
Instead, simply add it to the classpath of your root build.gradle file.
Check the usage for an example of how to add it to your classpath instead of applying the plugin:
https://github.com/runningcode/fladle#usage
