### ISSUE TITLE
Invalid YAML when providing projectId

### ISSUE THREAD

**Issue by andersu** [runningcode/fladle#49]
I just updated to Flank v5.1.0 and Fladle v0.6.0
In our fladle config in build.gradle we had 
`projectId("our-project-id")`

Flank did not like the YAML that was generated:
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.android.AndroidRunCommand@45afc369): com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: mapping values are not allowed here
 in 'reader', line 21, column 12:
        project: our-project-id
```

I think it might have to do with indentation because the line with `project: our-project-id` in the generated flank.yml was indented more than it should.

As a workaround I removed `projectId("our-project-id")` from our fladle config.
fladle still discovers the project id from the service account credentials.
The YAML generated this time was valid and everything worked again.

**Comment by runningcode** [comment]
Thanks for reporting. Please try fladle 0.6.1 and let me know if the issue is fixed!
