### ISSUE TITLE
Add support for tasks which run different test filters

### ISSUE THREAD

**Issue by runningcode** [runningcode/fladle#5]
Here are my thoughts on the API:
~~I was thinking of adding a map to the extension like so:~~
```
additionalTestFilters = mapOf(
  "pr" to listOf(listOf("class .........", "package......."))
  "regression" to listOf("class .........", "package......."))
)
```

~~this would generate two additional tasks~~
~~`runFlankPr` and `runFlankRegression` in addition to the `runFlank` task which would run with the default `testFilters`.~~

Let's use customizable tasks instead.

**Comment by winterDroid** [comment]
Ah yeah I see what you mean. Honestly I think that is not really necessary since that is what customizable tasks are made for, right?
