### ISSUE TITLE
`shardTime` config property not written to flank.yml

### ISSUE THREAD

**Issue by nnoel-grubhub** [runningcode/fladle#52]
While `shardTime` is present in the gradle plugin's configuration properties, it is not supported in FlankGradleExtension or YamlWriter. It will not be written to flank.yml properly as `shard-time`

This prevents the ability to use `shardTime` to dynamically set the shardCount.

**Comment by nnoel-grubhub** [comment]
Fixed by https://github.com/runningcode/fladle/pull/53 
@runningcode Will another release of this plugin be released with this change?

**Comment by runningcode** [comment]
Should already be released under 0.6.2! Please try it!

Nick Noel <notifications@github.com> schrieb am Do., 23. Mai 2019, 18:07:
