### ISSUE TITLE
Question: Do I have to set serviceAccountCredentials?

### ISSUE THREAD

**Issue by tir38** [runningcode/fladle#55]
On Flank docs I see that I can set service account credentials locally and for CI using some env vars https://github.com/TestArmada/flank#authenticate-with-a-service-account

If I'm using Fladle can I do this instead of supplying `serviceAccountCredentials("${project.file(....)` in build.gradle?

**Comment by runningcode** [comment]
I don't think it is currently supported. I think fladle fails fast if there are no service account credentials in the fladle extension in gradle. 
But please try it out and let me know how if it works for your use case. If it doesn't work, let me know how it fails and we can probably fix it!

**Comment by runningcode** [comment]
0.6.3 has been released with a fix, let me know if it solves this issue. Note, you must set the project id if the serviceAccountCredentials are not set using the fladle extension.
