### ISSUE TITLE
Feature Request: print location of html report when finished

### ISSUE THREAD

**Issue by tir38** [runningcode/fladle#64]
This kinda got asked for hiding in this other issue: 

https://github.com/runningcode/fladle/issues/45#issuecomment-479987954

It would be helpful if the HTML report location was printed out. I didn't even know until today that Flank generated an html report! This would have been more noticable.

**Comment by runningcode** [comment]
I didn't know about this either, is this a flag you can set on flank itself? What is the flag?

**Comment by runningcode** [comment]
I'm guessing this needs to be a feature request on flank itself. If Flank were to print it out, then Fladle would print it out as well.

**Comment by runningcode** [comment]
I've submitted this as a feature request upstream: https://github.com/TestArmada/flank/issues/592

**Comment by bootstraponline** [comment]
This feature has landed on Flank master and will be in the next release.

**Comment by runningcode** [comment]
Fixed in fladle 0.8.0 which uses flank 8.1.0!

**Comment by tir38** [comment]
Finally got around to updating to 0.8.0. Looks nice
