### ISSUE TITLE
Support multiple modules

### ISSUE THREAD

**Issue by winterDroid** [runningcode/fladle#7]
It would be great to support mult-module builds with multiple instrumentation APKs but a single debugApk.

**Comment by winterDroid** [comment]
@runningcode what do you think about having a dedicated `runFlank` task per module where the plugin is added? There could be a global configuration for all tasks in the project by the extension. Then there should be another configuration in the task itself e.g. with `testTargets`. Having something like:
```
// Everything from `FlankGradleExtension` still supported and used as default for the tasks
// Tries to find the debug and instrumentation apk from the applied project (for libraries just instrumentationApk?)
fladle {
    serviceAccountCredentials("${project.file("flank-gradle-5cf02dc90531.json")}")
    useOrchestrator = false
    devices = [
            new Device("NexusLowRes", 28, null, null),
            new Device("Nexus5", 23, null, null)
    ]
}

// Task with all the defaults from `fladle` will be added to the project
// Should it be possible to override the default task?
// task runFlank(type: FlankTask)

task runFlankCustomized(type: FlankTask) {
    // Overriding arguments of `fladle` supported for
    // - `useOrchestrator`
    // - `devices`
    // - `testTargets`
    testTargets = [
            "class com.osacky.flank.gradle.sample.ExampleInstrumentedTest#seeView"
    ]
    devices = [
            new Device("Nexus7", 28, null, null)
    ]
}
```

**Comment by runningcode** [comment]
Sounds like a good idea! This way fladle can be applied to the root project and then it will automatically generate a `runFlank` task for each subproject.

I think the root configuration extension should be 
``` 
fladle {
  serviceAccountCredentials("foo")
}
```

and then the per-module configuration can be
``` 
fladleModule {
  testTargets = [
    "class com.xxxxxx"
  ]
}
```

I think that's what you're getting at but with a slightly different api syntax? How does that sound?

**Comment by winterDroid** [comment]
The `fladeModule` idea sounds also great. Maybe let's have one root `flade` extension, the `fladeModule` extension and then the possibility to override per task. I'd need the override per task since e.g. we want to run screenshot tests and normal ui test separately thus with different testTargets in the same module. Are you fine with that? Which configuration options would you prefer in the two configuration extensions and the tasks?

**Comment by runningcode** [comment]
I was thinking the `fladleModule` extension would be the override. And maybe it just inherits from the regular `FlankGradleExtension`?
Maybe testTargets/debugApk/instrumentationApk should be  part of the module and not the base extension?
We can play around and see how we like the API.

**Comment by winterDroid** [comment]
Yeah for now that should be fine. I would just like to still add the possibility to override the `testTargets` in the task itself. Are you fine with that?

**Comment by runningcode** [comment]
Yeah, shouldn't that be possible by configuring the per module extension?

Marc Prengemann <notifications@github.com> schrieb am Do., 20. Sep. 2018
10:46:

**Comment by winterDroid** [comment]
Not if there will be multiple tasks to run flank with different testTargets in one module. Imagine you want to have one setup to run some tests on a PR and the full suite nightly.

**Comment by runningcode** [comment]
Ah, I see what you mean. I think that's a separate issue. I had a different
idea on how to approach that but I'm on mobile now Ill write an explanation
for it later.

Marc Prengemann <notifications@github.com> schrieb am Do., 20. Sep. 2018
10:57:

**Comment by runningcode** [comment]
@winterDroid I think what you are asking for is issue #5 ?

I've added a description detailing a proposed API in that issue. Let me know what you think!

**Comment by runningcode** [comment]
Closing since it isn't supported by FTL

**Comment by tir38** [comment]
Yeah what we had to do was add fladle to every module then just run them as separate gradle tasks

```
./gradlew module1:assembleAndroidTest module1:runFlank
./gradlew module2:assembleAndroidTest module2:runFlank
...
```
