### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by pjakubczyk** [runningcode/fladle#78]
Hi

I'm trying to setup code coverage with FTL usage. I read the tutorial on Flank page
https://github.com/TestArmada/flank#android-code-coverage

I thought I'm almost there but one thing is missing `results-dir: coverage_ec`
Since the value is not set via `FladleExtension` Flank falls back to `results-dir: null`

I'm not 100% sure if I'm obligated to set `results-dir` to actually run code coverage but definitely this value is missing from the extension.

Is there any hack I could use?
Thanks

**Comment by runningcode** [comment]
OH wow, I see a lot of thumbs up on this issue. PRs are very welcome!

You could probably do a hack where you rewrite this line in the yaml config by adding a doLast action to the writeConfigProps task.

**Comment by runningcode** [comment]
Please take a look at the PR. Is that what you are looking for?
I'll merge as soon as I get a 👍 https://github.com/runningcode/fladle/pull/80

**Comment by pjakubczyk** [comment]
Hey it turns this value is not `required` to generate the coverage. 
There is bigger problem with accessing sdcard using Firebase Emulators. I will keep you posted so we could update docs :D

**Comment by pjakubczyk** [comment]
@runningcode  it turned to be documentation problem on Flank side.
I made a PR that extends it https://github.com/TestArmada/flank/pull/617
also I could create a snippet for this repo too? wdyt?
