### ISSUE TITLE
Add maxTestShards variable to FlankGradleExtension

### ISSUE THREAD

**Issue by japplin** [runningcode/fladle#81]
I would like to be able to specify the maxTestShards in gradle.

**Comment by runningcode** [comment]
You can set `testShards` in the Fladle extension which writes the `max-test-shards` property to the Flank configuration.

**Comment by japplin** [comment]
When I set testShards in conjunction with the smart bucket it wasn't able to create fewer shards than the number specified in testShards.

**Comment by runningcode** [comment]
hmm, when you run the gradle task printYml, do you see that the `max-test-shards` property is set?

**Comment by runningcode** [comment]
I'm going to close out this issue for inactivity. Feel free to reopen if you are still seeing this.
