### ISSUE TITLE
Question: How can I get the runFlank task to fail upon receiving Google Cloud API errors?

### ISSUE THREAD

**Issue by SeptimusX75** [runningcode/fladle#82]
I've run the `runFlank` task and have received the following error:
```
Request failed, retrying 10x Request failed, retrying 10x com.google.api.client.googleapis.json.GoogleJsonResponseException: 429 Too Many Requests
{
  "code" : 429,
  "errors" : [ {
    "domain" : "global",
    "message" : "Insufficient test quota. See http://firebase.google.com/pricing/ for details.",
    "reason" : "rateLimitExceeded"
  } ],
  "message" : "Insufficient test quota. See http://firebase.google.com/pricing/ for details.",
  "status" : "RESOURCE_EXHAUSTED"
}
```
I would expect the task to fail after reaching the retry limit. That doesn't seem to be the case. Would there be a way to enable this? Otherwise, my CI job just hangs indefinitely.

**Comment by runningcode** [comment]
Thanks for the bug report.
So if you don't have test quota, are you saying that the flank executable never returns an exit code?
What version of Flank are you using? What version of Fladle are you using?
This is likely a bug in Flank, if Flank is not returning an exit code in certain conditions.

**Comment by runningcode** [comment]
Hey, if you have any information, please fill it in so I can help. Repro steps are especially helpful. Otherwise, I will close this ticket on Febrary 6th.

**Comment by pawelpasterz** [comment]
Hey I think that was flank itself that caused your issue. Recently we fixed case where flank was stuck for some errors. Please take a look https://github.com/Flank/flank/issues/649

**Comment by runningcode** [comment]
Thanks for fixing. I will close this issue.
