### ISSUE TITLE
Fladle dependency on AGP should be compileOnly

### ISSUE THREAD

**Issue by technoir42** [runningcode/fladle#86]
Currently Fladle has an `implementation` dependency on AGP:
```gradle
dependencies {
  implementation("com.android.tools.build:gradle:3.5.3")
}
```
If a project which applies Fladle uses a lower version of AGP, e.g. 3.5.1, Gradle will silently use the higher version which comes from Fladle instead of version 3.5.1, specified by user. This is definitely not something that the user would expect.

Gradle devs recommend using `compileOnly` configuration for dependencies provided by user:
https://blog.gradle.org/introducing-compile-only-dependencies

**Comment by runningcode** [comment]
Oh hey. You are definitely correct on this. I think I tried using `compileOnly` instead of `implementation` and ran in to some issues but I can't remember what they were.
Can you go ahead and make the change as a PR? If it passes the checks, I'll merge.

**Comment by runningcode** [comment]
This can be tricky. See this thread for more details: https://github.com/slackhq/keeper/pull/11#issuecomment-579544375
