### ISSUE TITLE
Fladle / Gradle not looking for Flank snapshot in correct place

### ISSUE THREAD

**Issue by tir38** [runningcode/fladle#99]
Using Fladle 0.9.1, If i set flank version `flankVersion = "flank_snapshot"` Gradle will complain about not finding artifact:

```
   > Could not find flank:flank:flank_snapshot.
     Searched in the following locations:
       - https://dl.bintray.com/flank/maven/flank/flank/flank_snapshot/flank-flank_snapshot.pom
       - https://jcenter.bintray.com/flank/flank/flank_snapshot/flank-flank_snapshot.pom
     Required by:
         project :app
```

If I understand the package structure right, it should be looking in

`https://dl.bintray.com/flank/maven/com/github/flank/flank/flank_snapshot/`

FWIW this is my top-level build.gradle file:

```
buildscript {
    repositories {
        google {
            ...
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        jcenter()
    }

    dependencies {
        ...
        
        classpath "com.osacky.flank.gradle:fladle:0.9.1"
    }
}

allprojects {
    repositories {
        google {
            ...
        }
        maven {
            url 'https://dl.bintray.com/flank/maven'
        }

        jcenter()
    }
}
```

**Comment by runningcode** [comment]
Yeah, apologies. Flank has changed their maven coordinates. In the future, flank will have the maven coordinates "com.github.flank:flank".
In order to accomodate past, current, and future maven coordinate changes, you can now specify `flankCoordinates = "com.github.flank:flank"` in fladle config.
https://github.com/runningcode/fladle#flankcoordinates

**Comment by runningcode** [comment]
Thanks for the quick feedback and for testing out the snapshot! Let me know if you have any troubles with the new api. There are also some more minor api changes upcoming. Check out the outstanding pull requests if you have a chance!

**Comment by runningcode** [comment]
Going to close. If this is still an issue, please re-open!
